# Generated by Django 5.1.2 on 2024-11-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection1',
            fields=[
                ('user_id', models.IntegerField()),
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionItems1',
            fields=[
                ('collection_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_url', models.URLField()),
                ('image_url', models.URLField()),
                ('brand_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('seller_id', models.IntegerField()),
                ('seller_name', models.CharField(max_length=255)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collection')),
            ],
        ),
    ]
