# Generated by Django 5.1.2 on 2024-11-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_collection1_delete_collectionitems1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitems',
            name='collection_id',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionItems',
        ),
    ]
