# Generated by Django 5.1.3 on 2024-11-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitems',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionitems',
            name='product_url',
            field=models.CharField(max_length=255),
        ),
    ]
