# Generated by Django 5.1.3 on 2024-11-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_collectionitems_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitems',
            name='image_url',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='collectionitems',
            name='product_url',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
