# Generated by Django 5.1.3 on 2024-11-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_collectionitems_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitems',
            name='SKU',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='collectionitems',
            name='UpdatePrice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='collectionitems',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
