# Generated by Django 5.1.3 on 2024-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_updateprice_collectionitems_oldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitems',
            name='SKU',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionitems',
            name='price',
            field=models.FloatField(),
        ),
    ]
