# Generated by Django 5.1.3 on 2024-12-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_collectionitems_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryCommision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_ids', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='collectionitems',
            name='origin',
            field=models.CharField(default='https://www.daraz.pk', max_length=100),
        ),
        migrations.AlterField(
            model_name='collectionitems',
            name='product_name',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
