"""
Django settings for MultiPlatformSeller project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lm49dsc)kx^(jlq8=8eu9=422nk7)q%z!-q2-fv%8+rijis%i3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Research',
    'rest_framework',
    'corsheaders',
    'api',
    'widget_tweaks',
    # 'django_cron',


]
CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
        'django.middleware.common.CommonMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]
# CRONJOBS = [
#     ('0 0 * * *', 'Research.cron.PriceChangeCheckCronJob')  # Run every day at midnight
# ]

CORS_ALLOWED_ORIGINS = [
    "https://www.daraz.pk", 
    "https://www.daraz.lk", 
    "https://www.daraz.com.bd", 
    "https://www.daraz.com.np", 
    "https://www.lazada.com.my", 
    "https://www.lazada.com.ph", 
    "https://www.lazada.sg", 
    "https://www.lazada.co.th", 
    "https://www.lazada.co.id", 
    'http://127.0.0.1:5500',  # Don't include the trailing slash
    'http://localhost:5500',
    'http://localhost:8000',  # Django local server URL
    'http://127.0.0.1:8000', 
]

# Allow cookies to be sent along with requests
CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'MultiPlatformSeller.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MultiPlatformSeller.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    # 'default': { 
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'MultiPlatformSeller', 
    #     'USER':'root', 
    #     'PASSWORD': '', 
    #     'HOST': '127.0.0.1',
    #      'PORT': '3306', 
    #     'OPTIONS': {
    #         'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",'ssl': {'ca': None} 
    #     }
    #     }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'

# MEDIA_ROOT defines the directory where uploaded media files are stored.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Gmail's SMTP server
EMAIL_PORT = 587  # Use 587 for TLS, 465 for SSL
EMAIL_USE_TLS = True  # Use TLS (recommended for Gmail)
EMAIL_HOST_USER = 'drivehunt0@gmail.com'  # Your Gmail address
EMAIL_HOST_PASSWORD = 'wwbq fadg pnvm guwx'  # Your Gmail password or App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
