# Generated by Django 5.1.2 on 2024-11-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('item_id', models.CharField(max_length=255, unique=True)),
                ('original_price', models.FloatField(default=-1)),
                ('price', models.FloatField(default=-1)),
                ('discount', models.CharField(default=' off', max_length=255)),
                ('rating', models.FloatField(default=0)),
                ('review', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('seller_id', models.CharField(blank=True, max_length=255)),
                ('item_sold', models.CharField(default='0 sold', max_length=255)),
                ('item_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('ProductQty1w', models.CharField(max_length=255, unique=True)),
                ('ProductQty1m', models.CharField(max_length=255, unique=True)),
                ('ProductQtyStd', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
